### ISSUE TITLE
Allow custom properties

### ISSUE THREAD

**Issue by dominikbulaj** [ultimate-pagination/react-ultimate-pagination#13]
Hi
First of all - thank you for creating one of coolest pagination components for React. 

As one of requirement in our project I have to display not page numbers but ranges (of content it display). I was able to do it with some function
```javascript 
const pageLabel = page => {
  const firstPage = ((page - 1) * 20) + 1
  const lastPage = firstPage + 19
  return `${firstPage}-${lastPage}`
}
```
and it display nicely ranges 1-20 | 21-40 | 41-60 ...

However UI team wants to display not full range but actual number of content items - so something like: 1-20 | 21-40 | 41-43

I tried to pass down own property (named total) but I saw it's omitted. 

Is there any plans, possibility to pass own (custom) props down? I see code destructs only some properties and nothing more is being added https://github.com/ultimate-pagination/react-ultimate-pagination/blob/master/src/react-ultimate-pagination.js#L23

Thanks.

**Comment by dmytroyarmak** [comment]
Hi @dominikbulaj 

Thank you for creating this ticket. Your use case is very interesting. I haven't thought about it.

As you found out, currently there is no way to pass custom properties from pagination component to components that are used to render individual page buttons. But, there is a way to solve your issue without changing react-ultimate-pagination library (I'm not sure when I'll have time to extend the library and what is the best way to do so).

To solve your issue, you can use [context](https://reactjs.org/docs/context.html) to pass `pageSize` and `totalItems` from a component that knows about this properties and component that renders individual button.

Here is working codepen with proposed solution: https://codepen.io/dmytroyarmak/pen/LevBmv?editors=0010

You can see that here we have pagination component that accepts `pageSize` and `totalItems` instead of `totalPages` and renders buttons as you described: 
```
      <Pagination 
         currentPage={this.state.currentPage} 
         pageSize={this.state.pageSize}
         totalItems={this.state.totalItems}
         onChange={this.onPageChange}
       />
```

**Comment by dominikbulaj** [comment]
Thank you @dmytroyarmak it seems be nice solution.
